import os

import pytest

from smartrouter.classifier.engine import ClassifierEngine


def test_missing_model_returns_default() -> None:
    # Point to a path that definitely doesn't exist
    engine = ClassifierEngine(model_path="models/nonexistent_model.pkl")

    score = engine.score_prompt("This is a test prompt.")

    # Assert that when model is missing, default score of 0.5 is returned
    assert score == 0.5


def test_score_prompt_returns_valid_probability() -> None:
    # Uses the real model that was generated by train_classifier.py
    engine = ClassifierEngine(model_path="models/complexity_classifier.pkl")

    # This assumes models/complexity_classifier.pkl was generated.
    # If the file exists, test the scoring mechanism.
    if os.path.exists("models/complexity_classifier.pkl"):
        score_simple = engine.score_prompt("What is 2 + 2?")
        score_complex = engine.score_prompt(
            "Explain the theory of relativity in detail, including its mathematical foundations."
        )

        # Verify both scores are within valid probability bounds
        assert 0.0 <= score_simple <= 1.0
        assert 0.0 <= score_complex <= 1.0
    else:
        pytest.skip("Model not found, skipping probability test.")
